language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcpl-dev

install:
    - pip install coveralls
    - pip install astropy
    - python setup.py install
    - (cd test/iiinstrumentp && ./bootstrap && ./configure && make CPPFLAGS="$CPPFLAGS -D_XOPEN_SOURCE=500")

script: (cd test && coverage run --source=cpl TestRecipe.py && mv -f .coverage ..)

after_success: coveralls
